build:
    environment:
        mysql: 5.7
        php:
            - version: 7.2
    dependencies:
        before:
            - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
            - mysql test < ./tests/test.sql
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true

