sudo: false

language: php

php:
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql test < ./tests/test.sql

before_script:
  - curl -sS http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --verbose
